# Generated by Django 4.0.3 on 2022-03-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_client_ip_taskhistory_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='client_ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
